name: zomato
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      
    
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - run: npm install  
    - run: npm ci
    - name: Build artifact
      run: npm run build
    
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONAR_HOST_URL }}
        login: ${{ secrets.SONAR_TOKEN }}
    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
          project: 'zomato-clone'
          path: '.'
          format: 'HTML'
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
           name: Depcheck report
           path: ${{github.workspace}}/reports  
     
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
          name: my-artifact # Adjust this to match the name of your artifact
        
    - name: Publish to Nexus Artifactory
      env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
          # Use curl or any other tool to publish your artifact to Nexus Artifactory
          # Example:
          curl -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file my-artifact.jar https://nexus.example.com/repository/my-repo/my-artifact.jar 
